
openapi: 3.0.0
info:
  title: My API
  description: API Documentation with Swagger
  version: 1.0.0
paths:
  /api:
    get:
      summary: Returns a welcome message
      responses:
        '200':
          description: A JSON object with a welcome message
